// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/johannes-kuhfuss/probesvc/domain (interfaces: JobRepository)

// Package domain is a generated GoMock package.
package domain

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/johannes-kuhfuss/probesvc/domain"
	api_error "github.com/johannes-kuhfuss/services_utils/api_error"
)

// MockJobRepository is a mock of JobRepository interface.
type MockJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepositoryMockRecorder
}

// MockJobRepositoryMockRecorder is the mock recorder for MockJobRepository.
type MockJobRepositoryMockRecorder struct {
	mock *MockJobRepository
}

// NewMockJobRepository creates a new mock instance.
func NewMockJobRepository(ctrl *gomock.Controller) *MockJobRepository {
	mock := &MockJobRepository{ctrl: ctrl}
	mock.recorder = &MockJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepository) EXPECT() *MockJobRepositoryMockRecorder {
	return m.recorder
}

// DeleteById mocks base method.
func (m *MockJobRepository) DeleteById(arg0 string) api_error.ApiErr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", arg0)
	ret0, _ := ret[0].(api_error.ApiErr)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockJobRepositoryMockRecorder) DeleteById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockJobRepository)(nil).DeleteById), arg0)
}

// FindAll mocks base method.
func (m *MockJobRepository) FindAll(arg0 string) (*[]domain.Job, api_error.ApiErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].(*[]domain.Job)
	ret1, _ := ret[1].(api_error.ApiErr)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockJobRepositoryMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockJobRepository)(nil).FindAll), arg0)
}

// FindById mocks base method.
func (m *MockJobRepository) FindById(arg0 string) (*domain.Job, api_error.ApiErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", arg0)
	ret0, _ := ret[0].(*domain.Job)
	ret1, _ := ret[1].(api_error.ApiErr)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockJobRepositoryMockRecorder) FindById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockJobRepository)(nil).FindById), arg0)
}

// GetNext mocks base method.
func (m *MockJobRepository) GetNext() (*domain.Job, api_error.ApiErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNext")
	ret0, _ := ret[0].(*domain.Job)
	ret1, _ := ret[1].(api_error.ApiErr)
	return ret0, ret1
}

// GetNext indicates an expected call of GetNext.
func (mr *MockJobRepositoryMockRecorder) GetNext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNext", reflect.TypeOf((*MockJobRepository)(nil).GetNext))
}

// Save mocks base method.
func (m *MockJobRepository) Save(arg0 domain.Job) api_error.ApiErr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(api_error.ApiErr)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockJobRepositoryMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockJobRepository)(nil).Save), arg0)
}

// SetResult mocks base method.
func (m *MockJobRepository) SetResult(arg0, arg1 string) api_error.ApiErr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResult", arg0, arg1)
	ret0, _ := ret[0].(api_error.ApiErr)
	return ret0
}

// SetResult indicates an expected call of SetResult.
func (mr *MockJobRepositoryMockRecorder) SetResult(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResult", reflect.TypeOf((*MockJobRepository)(nil).SetResult), arg0, arg1)
}

// SetStatus mocks base method.
func (m *MockJobRepository) SetStatus(arg0 string, arg1 domain.JobStatusUpdate) api_error.ApiErr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", arg0, arg1)
	ret0, _ := ret[0].(api_error.ApiErr)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockJobRepositoryMockRecorder) SetStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockJobRepository)(nil).SetStatus), arg0, arg1)
}
